/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemparkirclient;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import object.IClient;

/**
 *
 * @author Kid
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnoidentitas = new javax.swing.JTextField();
        ctgllahir = new org.jdesktop.swingx.JXDatePicker();
        cb_jenis = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jalamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jnohp = new javax.swing.JTextField();
        cb_jk = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 100, 35, 15);

        jnama.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(jnama);
        jnama.setBounds(170, 100, 170, 21);

        jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 420, 90, 23);

        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel2.setText("Add Customer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(88, 32, 210, 25);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Lahir");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 79, 15);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Identitas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 170, 82, 15);

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setText("Nomor Identitas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 210, 98, 17);

        jnoidentitas.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(jnoidentitas);
        jnoidentitas.setBounds(170, 210, 170, 21);

        ctgllahir.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        ctgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctgllahirActionPerformed(evt);
            }
        });
        getContentPane().add(ctgllahir);
        ctgllahir.setBounds(170, 130, 170, 23);

        cb_jenis.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        cb_jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KTP", "SIM", "Kartu Pelajar", " " }));
        getContentPane().add(cb_jenis);
        cb_jenis.setBounds(170, 170, 170, 21);

        jScrollPane1.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N

        jalamat.setColumns(20);
        jalamat.setRows(5);
        jScrollPane1.setViewportView(jalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 240, 170, 96);

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 41, 15);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setText("Nomor HP");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 350, 63, 17);

        jnohp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jnohp);
        jnohp.setBounds(170, 350, 170, 23);

        cb_jk.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        cb_jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));
        getContentPane().add(cb_jk);
        cb_jk.setBounds(170, 380, 170, 21);

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 380, 79, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SaveCustomer() 
    {
         try
         {
            Registry myRegistry = LocateRegistry.getRegistry("127.0.0.1", 9999);
            IClient f = (IClient) myRegistry.lookup("log");
            System.out.println("cool");
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String nama  = jnama.getText().toString();
            String tgl = df.format(ctgllahir.getDate());
            String jenisidentitas = cb_jenis.getSelectedItem().toString();
            String noidentitas = jnoidentitas.getText().toString();
            String alamat = jalamat.getText().toString();
            String nohp = jnohp.getText().toString();
            String jk = cb_jk.getSelectedItem().toString();
            
            
            
            
            f.setNama(nama);
            f.setTglLahir(tgl);
            f.setJenisIdentitas(jenisidentitas);
            f.setNoIdentitas(noidentitas);
            f.setAlamat(alamat);
            f.setNoHp(nohp);
            f.setJenisKelamin(jk);
            
        System.out.println("cool");
            
            int i = f.SaveCustomer();
            
            if(i != 0)
            {
                System.out.println("cool");
                JOptionPane.showMessageDialog(null, "Success");
                
            }
            else
            {
                  JOptionPane.showMessageDialog(null, "Error");
            }
             
         }
         catch(Exception ex)
         {
             JOptionPane.showMessageDialog(null,"Error asdsad: " + ex);
         }
         
         
         
     }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            SaveCustomer();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ctgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctgllahirActionPerformed
        // TODO add your handling code here:
         DateFormat df = new SimpleDateFormat("yyyy-mm-dd");
         
    }//GEN-LAST:event_ctgllahirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_jenis;
    private javax.swing.JComboBox cb_jk;
    private org.jdesktop.swingx.JXDatePicker ctgllahir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jalamat;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jnohp;
    private javax.swing.JTextField jnoidentitas;
    // End of variables declaration//GEN-END:variables
}
