/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemparkirclient;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import object.IClient;

/**
 *
 * @author Kid
 */
public class ListAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ListAdmin
     */
    public ListAdmin() {
        initComponents();
         Object columnName[] = {"ID Admin","Nama","Username","Password","Jenis Kelamin","Tanggal Lahir","Status"};
        DefaultTableModel model =  new DefaultTableModel(columnName,0);
        jTable1.setModel(model);
        popolatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 250, 40);

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 60, 20);

        jTextField1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 140, 160, 21);

        jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 140, 90, 23);

        jTable1.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 930, 270);

        jButton2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 140, 90, 23);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 140, 55, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kid\\Documents\\NetBeansProjects\\SistemParkirClient\\src\\imgprk\\2560x1440-black-solid-color-background.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 1010, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void popolatetable2()
    {
        try 
        {
           Registry reg = LocateRegistry.getRegistry("127.0.0.1", 9999);
            IClient obj = (IClient) reg.lookup("log");
            String search = jTextField1.getText();
            obj.setIDAdmin(search);
            ArrayList data = obj.getAdminID();
            
            
            //jTable1.setModel(DbUtils.resultSetToTableModel(data));
           //System.out.println(data.);
           if (!data.isEmpty())
           {
               JOptionPane.showMessageDialog(null, "Data Found" ); 
               for (int i = 0; i< data.size(); i+=7)
           {
               System.out.println("COOL");
               String idadmin = data.get(i).toString();
               String nama = data.get(i+1).toString();
               String username = data.get(i+2).toString();
               String password = data.get(i+3).toString();
               String jk = data.get(i+4).toString();
               String tgllahir = data.get(i+5).toString();
               String status = data.get(i+6).toString();
               
               
               
               String[] data_field = {idadmin, nama, username, password, jk,tgllahir,status};
               
               DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
               model.addRow(data_field);
           }
           }
           else{
               JOptionPane.showMessageDialog(null, "Data Not Found" );
           }
           
            
        } 
        catch (Exception e) {
            System.err.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
     private void popolatetable()
    {
        try 
        {
           Registry reg = LocateRegistry.getRegistry("127.0.0.1", 9999);
            IClient obj = (IClient) reg.lookup("log");
            ArrayList data = obj.getAdmin();
            
           for (int i = 0; i< data.size(); i+=7)
           {
               System.out.println("COOL");
              String idadmin = data.get(i).toString();
               String nama = data.get(i+1).toString();
               String username = data.get(i+2).toString();
               String password = data.get(i+3).toString();
               String jk = data.get(i+4).toString();
               String tgllahir = data.get(i+5).toString();
               String status = data.get(i+6).toString();
               
               
               String[] data_field = {idadmin, nama, username, password, jk,tgllahir,status};
               
               DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
               model.addRow(data_field);
           }
            
        } 
        catch (Exception e) {
            System.err.println(e);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
          popolatetable2();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        popolatetable();
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HomeSuperAdmin cs = new HomeSuperAdmin();
        cs.setLocationRelativeTo(null);
        cs.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
