/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemparkirclient;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Period;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import object.IClient;

/**
 *
 * @author Kid
 */
public class ParkirKeluar extends javax.swing.JFrame {

    /**
     * Creates new form ParkirKeluar
     */
    public ParkirKeluar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tx_plat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_masuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_keluar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tx_biaya = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tx_jenis = new javax.swing.JTextField();
        tx_bayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tx_kembalian = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_kembalian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel1.setText("Plat Nomor :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 100, 100, 15);

        tx_plat.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_plat);
        tx_plat.setBounds(160, 100, 160, 21);

        jButton1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 420, 90, 23);

        jLabel2.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel2.setText("Parkir Sepeda Motor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 323, 44);

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setText("Masuk :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 50, 15);

        tx_masuk.setEditable(false);
        tx_masuk.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_masuk);
        tx_masuk.setBounds(160, 180, 250, 21);

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel4.setText("Keluar :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 50, 15);

        tx_keluar.setEditable(false);
        tx_keluar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_keluar);
        tx_keluar.setBounds(160, 220, 250, 21);

        jButton2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton2.setText("Kalkulasi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 260, 110, 23);

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel5.setText("Biaya :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 330, 50, 15);

        tx_biaya.setEditable(false);
        tx_biaya.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_biaya);
        tx_biaya.setBounds(120, 330, 110, 21);

        jButton3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 100, 80, 23);

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel7.setText("Jenis :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 140, 60, 15);

        tx_jenis.setEditable(false);
        tx_jenis.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_jenis);
        tx_jenis.setBounds(160, 140, 250, 21);

        tx_bayar.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        getContentPane().add(tx_bayar);
        tx_bayar.setBounds(300, 330, 110, 21);

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel8.setText("Bayar :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 330, 50, 15);

        tx_kembalian.setEditable(false);
        tx_kembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(tx_kembalian);
        tx_kembalian.setBounds(300, 370, 110, 23);

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel9.setText("Kembalian :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 370, 80, 15);

        btn_kembalian.setText("Kalkulasi");
        btn_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kembalian);
        btn_kembalian.setBounds(430, 330, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            JOptionPane.showMessageDialog(null,"Success");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void popolatetable2()
    {
        try 
        {
            
           Registry reg = LocateRegistry.getRegistry("127.0.0.1", 9999);
            IClient obj = (IClient) reg.lookup("log");
            String plat = tx_plat.getText();
            obj.setPlatNomor(plat);
            
           ArrayList data = obj.getDataKendaraan();
           
           if (!data.isEmpty())
           {
                JOptionPane.showMessageDialog(null, "Data Found" );
                tx_plat.setText(data.get(1).toString());
                tx_jenis.setText(data.get(2).toString());
                tx_masuk.setText(data.get(3).toString());
                tx_keluar.setText(data.get(4).toString());
                tx_biaya.setText(data.get(5).toString());

           }
           else{
                   JOptionPane.showMessageDialog(null, "Data Not Found" );
           }
        } 
        catch (Exception e) {
            System.out.println(e);
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date = new Date();
            String waktu = dateFormat.format(date); //2016/11/16 12:08:43;
            tx_keluar.setText(waktu);
            
            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 9999);
            IClient obj = (IClient) reg.lookup("log");
            
            
            
            String plat = tx_plat.getText();
            String masuk = tx_masuk.getText();
            String keluar = tx_keluar.getText();
            String jenis = tx_jenis.getText();
            
            obj.setPlatNomor(plat);
            obj.setWaktuKeluar(keluar);
            int data = obj.UpdateDataParkir();
            if(data > 0)
            {
                JOptionPane.showMessageDialog(null, "Calculating...." );
                obj.setPlatNomor(plat);
                ArrayList data1 = obj.getJumlahWaktu();
                if(!data1.isEmpty()){
                    tx_biaya.setText(data1.get(0).toString());
                }
                else{
                    JOptionPane.showMessageDialog(null, "Data not valid" );
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Not Found" );
            }
            
            
       }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try
        {
            popolatetable2();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalianActionPerformed
        // TODO add your handling code here:
        try{
            int biaya = Integer.parseInt(tx_biaya.getText());
            int bayar = Integer.parseInt(tx_bayar.getText());
            
            int hasil = bayar - biaya;
            
            String hasilfix = String.valueOf(hasil);
            tx_kembalian.setText(hasilfix);
        }
        catch(Exception e){
            System.out.println(e); 
        }
    }//GEN-LAST:event_btn_kembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkirKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkirKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkirKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkirKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkirKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kembalian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tx_bayar;
    private javax.swing.JTextField tx_biaya;
    private javax.swing.JTextField tx_jenis;
    private javax.swing.JTextField tx_keluar;
    private javax.swing.JTextField tx_kembalian;
    private javax.swing.JTextField tx_masuk;
    private javax.swing.JTextField tx_plat;
    // End of variables declaration//GEN-END:variables
}
